Update 0-custom_http_response_header

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,46 +1,84 @@
 #!/usr/bin/env bash
-# Configure Nginx so that its HTTP response
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-# Install nginx on your web-01
+# uncomment to see the script run in action
+#set -x
 
-# Update package information then install Nginx
-sudo apt-get -y update
-sudo apt-get -y install nginx
+echo -e "Updating and doing some minor checks...\n"
 
-# enabe the most restrictive profile that will allow the traffic
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# allowing nginx on firewall
 sudo ufw allow 'Nginx HTTP'
 
-echo "Hello World!" > /var/www/html/index.nginx-debian.html
-echo "Ceci n'est pas une error_page" > /usr/share/nginx/html/custom_404.html
-echo "server {
-    listen 80 default_server;
-    listen [::]:80 default_server;
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
 
-    root /var/www/html;
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
 
-    # Add index.php to the list if you are using PHP
-    index index.html index.htm index.nginx-debian.html;
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
 
-    server_name _;
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-    location / {
-        # First attempt to serve request as file, then
-        # as a directory, then fall back to displaying a 404.
-        try_files \$uri \$uri/ =404;
-    }
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-    error_page 404 /custom_404.html;
-    location = /custom_404.html {
-        root /var/www/html;
-        internal;
-    }
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
 
-    location /redirect_me {
-        return 301 https://www.youtube.com/watch?v=3lFkDc6dFoY;
-    }
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
 
-    add_header X-Served-By $hostname;
-}
-" > /etc/nginx/sites-enabled/default
-
-sudo systemctl restart nginx
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
